# Health Stats Part 4: Waist 2 Hip Ratios - Pandas Only

<!--- Write an explanation of the Waist To Hips Ratio statistic used by health professionals. Please include an explanation of what it is used for, exactly how it is calculated, and how to interpret the results. Note: Formmatting matters. Make this as professional as you can using Markdown.  --->

### Overview

*Waist to Hip Ratio* is one of the many calculations doctors use to determine whether or not a patient is overweight. This helps doctors assess if a patient's weight may be putting them at certain health risks. The ratio compares your waist circumference to your hip circumference. Essentially, it determines how much fat is stored in the area in and around your waist and hips.  

Your *Waist to Hip Ratio* can be calculated by dividing your waist circumference by your hip circumference as follows: 

 #### $ ratio_{w2h} = \frac{w}{h} $

After calculating your Waist to Hip Ratio using the formual, it can be compared to the chart: 

### Waist to Hip Ratio Chart: 
| Health Risk          | Women                                                              |  Men                                 
|:-------------------  |:-----------------------------------------------------------------|:------------------------------|
| **Low:**             |    0.80 or lower                                                 |   0.95 or lower
        |
| **Moderate:**        |    0.81 - 0.85                                                   |    0.96 - .99
        |
| **High:**            |    0.86 or higher                                                |    1.0 or higher                                                   

According to the World Health Organization, a health WHR is: 
  + 0.9 or less for men 
  + 0.85 or less for women
  
In both men and women, a WHR  or 1.0 or higher increases the risk for heart disease and other conditions that are linked to being overweight.

<a href = "https://www.healthline.com/health/waist-to-hip-ratio">Click here to see the source for the information provided above</a>
    
<img src = 'https://upload.wikimedia.org/wikipedia/commons/3/34/Abdominal_obesity_in_men.jpg' />

## Source Data

<!--- Replace the text below with a Markdown bullet list that defines the columns of the CSV file. Be sure to indicate the data type for each column. --->

+ **ID**:
 + unique idenitfier for each person 
 + integer
+ **Waist**: 
 + measured circumference of the waist in inches 
 + integer
+ **Hip**: 
 + measured circumference of the hip in inches 
 + integer
+ **Gender**: 
 + one letter indicator for male(M) or female(F) 
 + string

## Data Import

In [1]:
# Goal: Extract the data from the file
import pandas as pd
w2h_df = pd.read_csv("w2h_data.csv")
w2h_df
# use proper pandas function to read data from a CSV file to a DataFrame

    ID  Waist  Hip Gender
0    1     30   32      M
1    2     32   37      M
2    3     30   36      M
3    4     33   39      M
4    5     29   33      M
5    6     32   38      M
6    7     33   42      M
7    8     30   40      M
8    9     30   37      M
9   10     32   39      M
10  11     24   35      F
11  12     25   37      F
12  13     24   37      F
13  14     22   34      F
14  15     26   38      F
15  16     26   37      F
16  17     25   38      F
17  18     26   37      F
18  19     28   40      F
19  20     23   35      F

## Calculations

In [2]:
# Goal: For each row of data calculate and store the w2h_ratio and shape.

# Step 1: Make sure the columns are in correct data types - refer to previous parts for the correct data types
w2h_df.dtypes

ID         int64
Waist      int64
Hip        int64
Gender    object
dtype: object

In [5]:
# Step 2: calculate the 'W2H_Ratio' column using the 'waist' and 'Hip' columns
# waist / hip

W2H_Ratio = w2h_df['Waist']/w2h_df['Hip']
W2H_Ratio

0     0.937500
1     0.864865
2     0.833333
3     0.846154
4     0.878788
5     0.842105
6     0.785714
7     0.750000
8     0.810811
9     0.820513
10    0.685714
11    0.675676
12    0.648649
13    0.647059
14    0.684211
15    0.702703
16    0.657895
17    0.702703
18    0.700000
19    0.657143
dtype: float64

In [4]:
w2h_df['W2H_Ratio'] = W2H_Ratio
w2h_df

    ID  Waist  Hip Gender  W2H_Ratio
0    1     30   32      M   0.937500
1    2     32   37      M   0.864865
2    3     30   36      M   0.833333
3    4     33   39      M   0.846154
4    5     29   33      M   0.878788
5    6     32   38      M   0.842105
6    7     33   42      M   0.785714
7    8     30   40      M   0.750000
8    9     30   37      M   0.810811
9   10     32   39      M   0.820513
10  11     24   35      F   0.685714
11  12     25   37      F   0.675676
12  13     24   37      F   0.648649
13  14     22   34      F   0.647059
14  15     26   38      F   0.684211
15  16     26   37      F   0.702703
16  17     25   38      F   0.657895
17  18     26   37      F   0.702703
18  19     28   40      F   0.700000
19  20     23   35      F   0.657143

In [8]:
# Step 3: create the 'Shape' column based on the values off the 'W2H_Ratio' column - refer to previous parts for the logic

w2h_df['Shape'] = 'Pear'
w2h_df.loc[(w2h_df['Gender'] == 'M') & (w2h_df['W2H_Ratio']>0.9) | (w2h_df['Gender'] == 'F') & (w2h_df['W2H_Ratio']>0.8),'Shape']='Apple'

## Output

In [9]:
# Goal: pretty print the rows as an HTML table

# Display the complete DF

# Save the DF to a file './complete_w2h.csv'
w2h_df

    ID  Waist  Hip Gender  W2H_Ratio  Shape
0    1     30   32      M   0.937500  Apple
1    2     32   37      M   0.864865   Pear
2    3     30   36      M   0.833333   Pear
3    4     33   39      M   0.846154   Pear
4    5     29   33      M   0.878788   Pear
5    6     32   38      M   0.842105   Pear
6    7     33   42      M   0.785714   Pear
7    8     30   40      M   0.750000   Pear
8    9     30   37      M   0.810811   Pear
9   10     32   39      M   0.820513   Pear
10  11     24   35      F   0.685714   Pear
11  12     25   37      F   0.675676   Pear
12  13     24   37      F   0.648649   Pear
13  14     22   34      F   0.647059   Pear
14  15     26   38      F   0.684211   Pear
15  16     26   37      F   0.702703   Pear
16  17     25   38      F   0.657895   Pear
17  18     26   37      F   0.702703   Pear
18  19     28   40      F   0.700000   Pear
19  20     23   35      F   0.657143   Pear

## Lessons Learned

Have you noticed in the previous two parts, how much code we have written? Have you also note how little code we have written in this part, with the help of Pandas? 

This is the reason why we want to use Pandas to handle the data we use for analytics.